# Generated by Django 6.0.3 on 2026-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participant_fee_paid_profile_creator_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='join_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('gift_card', 'Gift Card'), ('ingame', 'In-Game Item'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_participants',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='creatormembership',
            name='plan',
            field=models.CharField(choices=[('1month', '1 Month - 5 Tournaments'), ('3month', '3 Months - 15 Tournaments'), ('1year', '1 Year - Unlimited Tournaments')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creator_plan',
            field=models.CharField(choices=[('none', 'No Plan'), ('1month', '1 Month'), ('3month', '3 Months'), ('1year', '1 Year')], default='none', max_length=20),
        ),
    ]
