# Generated by Django 6.0.3 on 2026-04-05 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournament_join_deadline_tournament_max_players_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('reason', models.CharField(choices=[('tournament_join', 'Tournament Join'), ('tournament_refund', 'Tournament Refund'), ('tournament_win', 'Tournament Win'), ('creator_share', 'Creator Share'), ('admin_share', 'Admin Share'), ('withdrawal', 'Withdrawal'), ('withdrawal_refund', 'Withdrawal Refund'), ('admin_topup', 'Admin Top Up')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
