# Generated by Django 6.0.3 on 2026-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
