# Generated by Django 6.0.3 on 2026-04-13 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction_category_transaction_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_new_tournaments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rewardcode',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardcode',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reward_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardcode',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournament'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.CharField(choices=[('tournament_join', 'Tournament Join'), ('tournament_refund', 'Tournament Refund'), ('tournament_win', 'Tournament Win'), ('creator_share', 'Creator Share'), ('admin_share', 'Admin Share'), ('membership_purchase', 'Membership Purchase'), ('withdrawal', 'Withdrawal'), ('withdrawal_refund', 'Withdrawal Refund'), ('admin_topup', 'Admin Top Up')], max_length=30),
        ),
        migrations.CreateModel(
            name='CreatorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'creator')},
            },
        ),
    ]
