# Generated by Django 6.0.3 on 2026-04-16 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_notify_new_tournaments_rewardcode_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trophies',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reward_type', models.CharField(choices=[('cash', 'Cash'), ('gift_card', 'Gift Card')], max_length=20)),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules', models.TextField()),
                ('eligibility_criteria', models.CharField(default='12000+ trophies', max_length=255)),
                ('min_trophies', models.IntegerField(default=12000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_players', models.IntegerField(default=32)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('bracket_generated', models.BooleanField(default=False)),
                ('bracket_locked', models.BooleanField(default=True)),
                ('shuffled_player_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cups_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CupJoinGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(max_length=100)),
                ('clan_tag', models.CharField(max_length=50)),
                ('instructions', models.TextField(help_text='How players should join and play friendly matches.')),
                ('cup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_guide', to='core.cup')),
            ],
        ),
        migrations.CreateModel(
            name='CupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('player1_label', models.CharField(blank=True, default='', max_length=100)),
                ('player2_label', models.CharField(blank=True, default='', max_length=100)),
                ('winner_label', models.CharField(blank=True, default='', max_length=100)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='cup_results/')),
                ('result_source', models.CharField(blank=True, choices=[('creator_proof', 'Creator + Proof'), ('dual_confirmation', 'Dual Confirmation'), ('auto_bye', 'Auto BYE Advance'), ('admin_override', 'Admin Override')], max_length=30, null=True)),
                ('next_slot', models.IntegerField(blank=True, help_text='1 for player1 slot, 2 for player2 slot', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_matches', to='core.cup')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='core.cupmatch')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_player1_matches', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_player2_matches', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_winner_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
                'unique_together': {('cup', 'round_number', 'match_number')},
            },
        ),
        migrations.CreateModel(
            name='CupActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_cup', 'Create Cup'), ('join_cup', 'Join Cup'), ('generate_matches', 'Generate Matches'), ('mark_winner', 'Mark Winner'), ('dual_confirm', 'Dual Confirm Result'), ('kick_player', 'Kick Player'), ('ban_player', 'Ban Player'), ('admin_override', 'Admin Override'), ('auto_advance_bye', 'Auto Advance BYE')], max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_actions', to=settings.AUTH_USER_MODEL)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='core.cup')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_target_actions', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='core.cupmatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CupMatchConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_cup_wins', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='core.cupmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CupParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophies_snapshot', models.IntegerField(default=0)),
                ('kicked', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.cup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cup', 'user')},
            },
        ),
    ]
