# Generated by Django 6.0.3 on 2026-04-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_trophies_cup_cupjoinguide_cupmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupmatch',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cupmatch',
            name='dispute_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cupmatch',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cupmatch',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cupmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('disputed', 'Disputed'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='cupmatchconfirmation',
            name='decision',
            field=models.CharField(choices=[('accept', 'Accept Result'), ('dispute', 'Dispute Result')], default='accept', max_length=20),
        ),
        migrations.AddField(
            model_name='cupmatchconfirmation',
            name='dispute_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cupparticipant',
            name='ingame_username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='ingame_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cupactionlog',
            name='action_type',
            field=models.CharField(choices=[('create_cup', 'Create Cup'), ('join_cup', 'Join Cup'), ('generate_matches', 'Generate Matches'), ('mark_winner', 'Mark Winner'), ('dual_confirm', 'Dual Confirm Result'), ('player_dispute', 'Player Dispute'), ('resolve_dispute', 'Resolve Dispute'), ('kick_player', 'Kick Player'), ('ban_player', 'Ban Player'), ('admin_override', 'Admin Override'), ('auto_advance_bye', 'Auto Advance BYE')], max_length=30),
        ),
    ]
