# Generated by Django 6.0.3 on 2026-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cupmatch_deadline_cupmatch_dispute_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='is_bracket_generated',
            field=models.BooleanField(default=False),
        ),
    ]
