# Generated by Django 6.0.3 on 2026-04-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cup_is_bracket_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
    ]
