# Generated by Django 6.0.3 on 2026-04-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification_url_profile_trust_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, help_text='Plan key for membership payments', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('wallet_topup', 'Wallet Top-up'), ('creator_membership', 'Creator Membership')], default='wallet_topup', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(default='MIGRATION', help_text='Unique reference ID e.g. CA1234', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='utr',
            field=models.CharField(blank=True, help_text='UPI Transaction Reference', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_via',
            field=models.CharField(blank=True, help_text='sms_auto or user_utr', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(blank=True, help_text='Raw timestamp from SMS forwarder', max_length=100)),
                ('parsed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parsed_utr', models.CharField(blank=True, max_length=30, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='core.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
