# Generated by Django 6.0.3 on 2026-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='utr',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_via',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, help_text='Cashfree Order ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20),
        ),
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
