# Generated by Django 6.0.3 on 2026-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_rewardcode_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reward_balance',
            new_name='deposit_balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='winnings_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_distributed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='order_id / tournament_id / withdrawal_id', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='success', help_text='pending, success, failed', max_length=20),
        ),
    ]
