# Generated by Django 6.0.3 on 2026-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_profile_device_fingerprint_profile_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
