# Generated by Django 6.0.3 on 2026-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of user balance after this transaction (Ledger Integrity)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='order_id / tournament_id / withdrawal_id (Idempotency Key)', max_length=100, null=True),
        ),
    ]
