# Generated by Django 6.0.3 on 2026-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_balance_after_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
